services:
  postgres:
    image: postgres:15-alpine
    container_name: onetee-postgres
    environment:
      POSTGRES_USER: onetee_user
      POSTGRES_PASSWORD: onetee_password
      POSTGRES_DB: onetee_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-09-13T20-26-02Z
    container_name: onetee-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console UI
    volumes:
      - ./minio_data:/data

volumes:
  postgres_data:
  minio_data: