"""add auth fields to user

Revision ID: 317deb2ec883
Revises: dc1a03449571
Create Date: 2025-08-18 01:48:14.359261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317deb2ec883'
down_revision: Union[str, Sequence[str], None] = 'dc1a03449571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('community_users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('community_users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('community_users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_community_users_email'), 'community_users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_users_email'), table_name='community_users')
    op.drop_column('community_users', 'is_admin')
    op.drop_column('community_users', 'is_active')
    op.drop_column('community_users', 'password_hash')
    op.drop_column('community_users', 'email')
    # ### end Alembic commands ###
