"""init community tables

Revision ID: dc1a03449571
Revises: 
Create Date: 2025-08-18 01:41:21.143193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1a03449571'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_hashtags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_hashtags_tag'), 'community_hashtags', ['tag'], unique=True)
    op.create_table('community_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_users_username'), 'community_users', ['username'], unique=True)
    op.create_table('community_follows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['community_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['community_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follow_pair')
    )
    op.create_index(op.f('ix_community_follows_follower_id'), 'community_follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_community_follows_following_id'), 'community_follows', ['following_id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('in_reply_to_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['community_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['in_reply_to_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_author_id'), 'community_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_posts_in_reply_to_id'), 'community_posts', ['in_reply_to_id'], unique=False)
    op.create_table('community_bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['community_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_bookmark_user_post')
    )
    op.create_index(op.f('ix_community_bookmarks_post_id'), 'community_bookmarks', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_bookmarks_user_id'), 'community_bookmarks', ['user_id'], unique=False)
    op.create_table('community_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['community_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_like_user_post')
    )
    op.create_index(op.f('ix_community_likes_post_id'), 'community_likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_likes_user_id'), 'community_likes', ['user_id'], unique=False)
    op.create_table('community_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('alt_text', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_media_post_id'), 'community_media', ['post_id'], unique=False)
    op.create_table('community_mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('mentioned_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['community_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_mentions_mentioned_user_id'), 'community_mentions', ['mentioned_user_id'], unique=False)
    op.create_index(op.f('ix_community_mentions_post_id'), 'community_mentions', ['post_id'], unique=False)
    op.create_table('community_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['community_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['community_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_notifications_actor_id'), 'community_notifications', ['actor_id'], unique=False)
    op.create_index(op.f('ix_community_notifications_post_id'), 'community_notifications', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_notifications_recipient_id'), 'community_notifications', ['recipient_id'], unique=False)
    op.create_table('community_post_hashtags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('hashtag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['community_hashtags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'hashtag_id', name='uq_post_hashtag')
    )
    op.create_index(op.f('ix_community_post_hashtags_hashtag_id'), 'community_post_hashtags', ['hashtag_id'], unique=False)
    op.create_index(op.f('ix_community_post_hashtags_post_id'), 'community_post_hashtags', ['post_id'], unique=False)
    op.create_table('community_reposts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['community_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_repost_user_post')
    )
    op.create_index(op.f('ix_community_reposts_post_id'), 'community_reposts', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_reposts_user_id'), 'community_reposts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_reposts_user_id'), table_name='community_reposts')
    op.drop_index(op.f('ix_community_reposts_post_id'), table_name='community_reposts')
    op.drop_table('community_reposts')
    op.drop_index(op.f('ix_community_post_hashtags_post_id'), table_name='community_post_hashtags')
    op.drop_index(op.f('ix_community_post_hashtags_hashtag_id'), table_name='community_post_hashtags')
    op.drop_table('community_post_hashtags')
    op.drop_index(op.f('ix_community_notifications_recipient_id'), table_name='community_notifications')
    op.drop_index(op.f('ix_community_notifications_post_id'), table_name='community_notifications')
    op.drop_index(op.f('ix_community_notifications_actor_id'), table_name='community_notifications')
    op.drop_table('community_notifications')
    op.drop_index(op.f('ix_community_mentions_post_id'), table_name='community_mentions')
    op.drop_index(op.f('ix_community_mentions_mentioned_user_id'), table_name='community_mentions')
    op.drop_table('community_mentions')
    op.drop_index(op.f('ix_community_media_post_id'), table_name='community_media')
    op.drop_table('community_media')
    op.drop_index(op.f('ix_community_likes_user_id'), table_name='community_likes')
    op.drop_index(op.f('ix_community_likes_post_id'), table_name='community_likes')
    op.drop_table('community_likes')
    op.drop_index(op.f('ix_community_bookmarks_user_id'), table_name='community_bookmarks')
    op.drop_index(op.f('ix_community_bookmarks_post_id'), table_name='community_bookmarks')
    op.drop_table('community_bookmarks')
    op.drop_index(op.f('ix_community_posts_in_reply_to_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_author_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_community_follows_following_id'), table_name='community_follows')
    op.drop_index(op.f('ix_community_follows_follower_id'), table_name='community_follows')
    op.drop_table('community_follows')
    op.drop_index(op.f('ix_community_users_username'), table_name='community_users')
    op.drop_table('community_users')
    op.drop_index(op.f('ix_community_hashtags_tag'), table_name='community_hashtags')
    op.drop_table('community_hashtags')
    # ### end Alembic commands ###
